export const apiRegister = 'auth/register'
export const apiLogin = 'auth/login'
export const apiCheckAuth = 'auth/check-auth'
export const apiGetDetailProfile = 'auth/me'
export const apiLogout = 'auth/logout'
